kind: Template
apiVersion: v1
metadata:
  name: rsync-cronjob
  annotations:
    description: >

parameters:
- name: APP_NAME
  value: ""
  description: "Name for the created resources as well ass for labeling app:<app name>"
- name: ENVIRONMENT
  value: "staging"
  description: "For labeling resources environment:<environment>"
- name: DOCKERHUB_IMAGE
  value: "secoresearch/rsync:latest"
  description: "rsync image in dockerhub"
- name: RSYNC_IMAGESTREAM
  value: "rsync"
  description: "ImageStream for the rsync image. If it does not exist, the image will be imported from dockerhub to this ImageStream"
- name: SSH_KEY_SECRET
  value: ""
  description: "OpenShift secret containing the SSH private key to use (if needed)"
- name: RSYNC_SOURCE
  value: "/m/"
  description: "Rsync source. E.g. /m/some-folder/ or user@server.example.org"
- name: RSYNC_TARGET
  value: "<rsync target>"
  description: "Target for rsync. E.g. /m/some-folder/ or user@server.example.org"
- name: RSYNC_OPTIONS
  value: "-avz"
  description: "Command line options to pass to rsync"

objects:
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: "${RSYNC_IMAGESTREAM}"
    labels:
      app: "${APP_NAME}"
      environment: "${ENVIRONMENT}"
  spec:
    lookupPolicy:
      local: true
    tags:
    - name: latest
      from:
        kind: DockerImage
        name: "${DOCKERHUB_IMAGE}"
      importPolicy:
        scheduled: true
      referencePolicy:
        type: Source
- kind: CronJob
  apiVersion: batch/v1beta1
  metadata:
    name: "${APP_NAME}"
    labels:
      app: "${APP_NAME}"
      environment: "${ENVIRONMENT}"
  spec:
    schedule: "*/2 * * * *"
    jobTemplate:
      spec:
        template:
          metadata:
            labels:
              environment: "${ENVIRONMENT}"
              name: "${APP_NAME}"
          spec:
            containers:
            - name: rsync
              image: "${RSYNC_IMAGESTREAM}:latest"
              env:
              - name: RSYNC_SOURCE
                value: "${RSYNC_SOURCE}"
              - name: RSYNC_TARGET
                value: "${RSYNC_TARGET}"
              - name: RSYNC_OPTIONS
                value: "${RSYNC_OPTIONS}"
            restartPolicy: OnFailure

