kind: Template
apiVersion: v1
metadata:
  name: rsync-cronjob
  annotations:
    description: >
      Rsync file or folder between a volume and a remote host.

parameters:
- name: CRONJOB_NAME
  value: ""
  description: "Name for the CronJob and other create resources"
- name: RSYNC_IMAGESTREAM
  value: "rsync"
  description: "ImageStream that contains the rsync image (import it from the dockerhub first)"
- name: SSH_KEY_SECRET
  value: ""
  description: "OpenShift secret containing the SSH private key to use (if needed)"
- name: PVC_NAME
  value: ""
  description: "PhysicalVolumeClaim to mount into the rsync container"
- name: PVC_TARGET
  value "/m/"
  description: "Path inside the rsync container to mount the PVC to"
- name: RSYNC_SOURCE
  value: "/m/"
  description: "Rsync source. E.g. /m/some-folder/ or user@server.example.org"
- name: RSYNC_TARGET
  value: "<rsync target>"
  description: "Target for rsync. E.g. /m/some-folder/ or user@server.example.org"
- name: RSYNC_OPTIONS
  value: "-avz"
  description: "Command line options to pass to rsync"

objects:
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: "${RSYNC_IMAGESTREAM}"
  spec:
    lookupPolicy:
      local: true
    tags:
    - name: latest
      from:
        kind: DockerImage
        name: "${DOCKERHUB_IMAGE}"
      importPolicy:
        scheduled: true
      referencePolicy:
        type: Source
- kind: CronJob
  apiVersion: batch/v1beta1
  metadata:
    name: "${CRONJOB_NAME}"
  spec:
    schedule: "*/2 * * * *"
    jobTemplate:
      spec:
        template:
          metadata:
          spec:
            containers:
            - name: rsync
              image: "${RSYNC_IMAGESTREAM}:latest"
              env:
              - name: RSYNC_SOURCE
                value: "${RSYNC_SOURCE}"
              - name: RSYNC_TARGET
                value: "${RSYNC_TARGET}"
              - name: RSYNC_OPTIONS
                value: "${RSYNC_OPTIONS}"
            restartPolicy: OnFailure

